<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ParametersManagement.LibParameters" Version="1.0.9686.34062" />
    <PackageVersion Include="ReplicatorShared.Data" Version="1.0.9686.36920" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
    <PackageVersion Include="Figgle.Fonts" Version="0.6.6" />
    <PackageVersion Include="SystemTools.BackgroundTasks" Version="1.0.9686.33588" />
    <PackageVersion Include="WebSystemTools.ApiExceptionHandler" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.SerilogLogger" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.SwaggerTools" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.TestToolsApi" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.WindowsServiceTools" Version="1.0.9686.34761" />
  </ItemGroup>
</Project>